from core.models import SummaryResult, Briefing
from core.a2a import Executor

def run_editor(input_data: SummaryResult) -> Briefing:
    lines = ["# News Briefing\n"]
    sources = []
    
    for i, summary in enumerate(input_data.summaries, 1):
        lines.append(f"## Story {i}")
        lines.append(f"{summary.summary}")
        lines.append(f"[Source Link]({summary.url})\n")
        sources.append(summary.url)
        
    lines.append("---\n*Note: This briefing was generated by A2A agents.*")
    
    content = "\n".join(lines)
    
    return Briefing(
        run_id=input_data.run_id,
        agent_name="EditorAgent",
        topic="Consolidated Briefing", # In a real system, we'd pass the topic through the agents
        content=content,
        sources=sources
    )

editor_executor = Executor(
    name="EditorAgent",
    func=run_editor,
    input_type=SummaryResult
)
